#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Glib
version:      1.060
version_from: Glib.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
