--- #YAML:1.0
name:                Glib
version:             1.180
abstract:            Perl wrappers for the GLib utility and Object libraries
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    ExtUtils::Depends:             0.200
    ExtUtils::PkgConfig:           1.00
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3

configure_requires:
   ExtUtils::Depends: 0.200
   ExtUtils::PkgConfig: 1.00

no_index:
    package:
    - MY
    file:
    - xsapi.pod.foot
    - Glib.xs
  - GError.xs
  - GUtils.xs
  - GLog.xs
  - GType.xs
  - GBoxed.xs
  - GObject.xs
  - GValue.xs
  - GClosure.xs
  - GSignal.xs
  - GMainLoop.xs
  - GIOChannel.xs
  - GParamSpec.xs
  - GKeyFile.xs
  - GBookmarkFile.xs
