#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Glib
version:      1.00rc2
version_from: Glib.pm
installdirs:  site
requires:
    ExtUtils::Depends:             0.1
    ExtUtils::PkgConfig:           1.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
