--- #YAML:1.0
name:               Glib
version:            1.201
abstract:           Perl wrappers for the GLib utility and Object libraries
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::Depends:    0.300
    ExtUtils::MakeMaker:  0
    ExtUtils::PkgConfig:  1.00
requires:
    ExtUtils::Depends:    0.300
    ExtUtils::PkgConfig:  1.00
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
