--- #YAML:1.0
name:                Glib
version:             1.143
abstract:            Perl wrappers for the GLib utility and Object libraries
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    ExtUtils::Depends:             0.200
    ExtUtils::PkgConfig:           1.00
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
