---
abstract: 'Perl wrappers for the GLib utility and Object libraries'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::Depends: 0.300
  ExtUtils::MakeMaker: 0
  ExtUtils::PkgConfig: 1.00
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Glib
no_index:
  directory:
    - t
    - inc
  file:
    - Glib.xs
    - GError.xs
    - GUtils.xs
    - GLog.xs
    - GType.xs
    - GBoxed.xs
    - GObject.xs
    - GValue.xs
    - GClosure.xs
    - GSignal.xs
    - GMainLoop.xs
    - GIOChannel.xs
    - GParamSpec.xs
    - GKeyFile.xs
    - GOption.xs
    - GBookmarkFile.xs
    - xsapi.pod.head
    - xsapi.pod.foot
  package:
    - MY
requires:
  ExtUtils::Depends: 0.300
  ExtUtils::PkgConfig: 1.00
version: 1.251
